CC=g++
TARGET=endian backlog testaccept testoobsend testoobrecv

all:${TARGET}

endian:endian.cc
backlog:backlog.cc
testaccept:testaccept.cc
testoobsend:testoobsend.cc
testoobrecv:testoobrecv.cc

.PHONY:clean
clean:
	rm ${TARGET}
